# Development application environment

---
apiVersion: v1
kind: Namespace
metadata:
  name: vms
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simulation-env
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/shaneboulden/tailspin-argocd-cd.git
    targetRevision: main
    path: overlays/development
  destination:
    namespace: vms
    server: https://kubernetes.default.svc