## sunshine

---
apiVersion: v1
kind: Service
metadata:
  name: win10-sunshine
spec:
  ports:
  - name: sunshine
    port: 47990
    protocol: TCP
    targetPort: 47990
  selector:
    vm.kubevirt.io/name: windows-10-virtio-tailspin
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sunshine
spec:
  to:
    kind: Service
    name: win10-sunshine
    weight: 100
  port:
    targetPort: sunshine
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None